version: '3.7'

services:
  webscrapper:
    build: /scrapping
    container_name: webscrapper
    depends_on:
      - postgres
    networks:
      - webscrapper-network

  postgres:
    build: 
      context: ./db
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - webscrapper-network
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - webscrapper-network
    depends_on:
      - postgres

networks:
  webscrapper-network:
    