FROM apache/airflow:slim-2.9.3-python3.10

COPY requirements.txt /opt/airflow/requirements.txt
COPY entrypoint.sh /opt/airflow/entrypoint.sh

USER root

RUN chmod +x /opt/airflow/entrypoint.sh

USER airflow
COPY dags /opt/airflow/dags
COPY utils /opt/airflow/utils
COPY setup.py /opt/airflow/setup.py

ENTRYPOINT ["/opt/airflow/entrypoint.sh"]
