---
- name: Deploy Docker container on VPS
  hosts: all
  become: true
  vars:
    docker_image: "{{ docker_image }}"
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Print docker_image variable
      debug:
        msg: "Docker image is {{ docker_image }}"
     
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        pull: yes

