---
- name: Deploy Docker container on VPS
  hosts: all
  become: true
  vars:
    docker_image: "nathanaelfr/webscraper:9853173602"
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Pull Docker image
      community.docker.docker_image_pull:
        name: "{{ docker_image }}"
        pull: yes
