---
- name: Deploy Docker container on VPS
  hosts: vps
  gather_facts: false
  become: true

  tasks:

    - name: Pull Docker image 
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop and remove existing container
      community.docker.docker_container:
        name: webscraper
        state: absent
      ignore_errors: yes

    - name: Run Docker container on VPS
      community.docker.docker_container:
        name: webscraper
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        image_name_mismatch: recreate
        env:
          AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
          S3_BUCKET_NAME: "{{ s3_bucket_name }}"

    - name: Grab container status
      community.docker.docker_container_info:
        name: webscraper
      register: container_info

    - name: Ensure the container is running
      assert:
        that:
          - container_info.container.State.Running
        msg: "The webscraper container is not running!"

    - name: Check environment variables inside the container
      shell: |
        docker exec webscraper python3 -c "import os; assert os.environ['AWS_ACCESS_KEY_ID'] == '{{ aws_access_key_id }}'"
        docker exec webscraper python3 -c "import os; assert os.environ['AWS_SECRET_ACCESS_KEY'] == '{{ aws_secret_access_key }}'"
        docker exec webscraper python3 -c "import os; assert os.environ['S3_BUCKET_NAME'] == '{{ s3_bucket_name }}'"

      ignore_errors: yes
