name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["Build, Push, and Test containers", "Test S3 Connection"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push webscraper image
      uses: docker/build-push-action@v3
      with:
        context: ./scrapping
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/webscraper:${{ github.run_id }}

    - name: Build and push postgres image
      uses: docker/build-push-action@v3
      with:
        context: ./db
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mypostgres:${{ github.run_id }}

  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

    - name: Test SSH connection
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_PORT: ${{ secrets.VPS_PORT }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        sshpass -p "${{ env.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ env.VPS_USER }}@${{ env.VPS_IP }} -p ${{ env.VPS_PORT }} "echo 'SSH connection successful!'"

  deploy:
    needs: [build-and-push, test-ssh]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install required collections
      run: |
        ansible-galaxy collection install community.general

    - name: Create dynamic inventory
      run: |
        cat <<EOF > ansible/inventories/setup.yml
        [vps]
        ${{ secrets.VPS_IP }}

        [vps:vars]
        ansible_ssh_user=${{ secrets.VPS_USER }}
        ansible_ssh_pass=${{ secrets.VPS_PASSWORD }}
        ansible_ssh_port=${{ secrets.VPS_PORT }}
        ansible_python_interpreter=/usr/bin/python3
        EOF

    - name: Run Ansible playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        PUSH_ID: ${{ github.run_id }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        ansible-playbook ansible/playbook.yml \
          -i ansible/inventories/setup.yml \
          -e "push_id=${{ env.PUSH_ID }}" \
          -e "dockerhub_username=${{ env.DOCKERHUB_USERNAME }}" \
          -e "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" \
          -e "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
          -e "s3_bucket_name=${{ env.S3_BUCKET_NAME }}" \
          -e "postgres_user=${{ secrets.POSTGRES_USER }}" \
          -e "postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
          -e "postgres_db=${{ secrets.POSTGRES_DB }}"


    - name: Test container running
      run: |
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} -p ${{ secrets.VPS_PORT }} "docker ps | grep webscraper"