name: Build, Push, and Run Docker container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/webscraper:${{ github.run_id }}

    - name: Run Docker container
      run: |
        docker run -d \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          -e S3_BUCKET_NAME=jobscrappingbucket \
          ${{ secrets.DOCKERHUB_USERNAME }}/webscraper:${{ github.run_id }}

    - name: Check running container 
      run: |
        docker ps -q | xargs docker inspect --format '{{ .State.Status }}'
        
    # - name: Check cron jobs in running container
    #   run: |
    #     docker ps -q | xargs docker exec $(docker ps -q) bash -c "crontab -l > /tmp/crontab_output && diff /app/crontab /tmp/crontab_output > /dev/null"
    #     if [ $? -ne 0 ]; then
    #       echo "cron jobs differ"
    #       exit 1
    #     fi
