name: Test S3 Connection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-s3-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Test S3 Connection
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET_NAME: jobscrappingbucket
        run: |
          python -c "
          import boto3
          import os

          s3 = boto3.client(
              's3',
              aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
              aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
              region_name=os.getenv('AWS_DEFAULT_REGION')
          )

          bucket_name = os.getenv('S3_BUCKET_NAME')
          try:
              s3.head_bucket(Bucket=bucket_name)
              print(f'Successfully connected to the bucket {bucket_name}')
          except Exception as e:
              print(f'Failed to connect to the bucket {bucket_name}: {e}')
              raise e
          "
